# 7.1 - NumPy (Ch7)
NumPy (Numerical Python) is a fundamental package for scientific computing and array-oriented programming with Python.

### Why NumPy?
- Enables fast numerical computations using arrays.
- Provides powerful array-oriented programming tools.
- Essential for working with large datasets and matrices.




Below is a visualization of how data is organized in a NumPy array (like a table):

```
Array:
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

Row 0 → [1, 2, 3]
Row 1 → [4, 5, 6]
Row 2 → [7, 8, 9]
```


## Importing NumPy

* We can use NumPy in our programs by importing it.
* It is common to give NumPy the identifier `np` using the `as` keyword.

In [1]:
import numpy as np

## NumPy Arrays vs Python Lists
- NumPy arrays are mutable, linear/sequence data structures similar to lists.
- NumPy arrays are more efficient than Python lists.
- They allow element-wise operations and broadcasting.
- They are typed and fixed-size for performance.


In [2]:
my_list = [1, 2, 3]
print("List:", my_list)

List: [1, 2, 3]


In [3]:
my_array = np.array([1, 2, 3])
print("NumPy Array:", my_array)

NumPy Array: [1 2 3]


- NumPy arrays are heterogeneous, i.e. can contain data of any type.
- They can also be defined using tuples.

In [4]:
my_array2 = np.array(("Hello", 35, 4.0))
print("NumPy Array 2:", my_array2)

NumPy Array 2: ['Hello' '35' '4.0']


## Creating and Inspecting Arrays

- Use `np.array()` to convert lists into NumPy arrays.

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


- You can also create arrays filled with zeros or ones:

In [6]:
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones = np.ones((3, 2))
print("Ones:\n", ones)

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


- You can also create arrays filled with any custom value:

In [8]:
filled = np.full((2, 2), 7)
print("Filled:\n", filled)

Filled:
 [[7 7]
 [7 7]]


- We can check properties like shape, dimensions, and data type.

In [9]:
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Data Type:", a.dtype)

Shape: (3, 2)
Dimensions: 2
Data Type: int64


- We can reshape a NumPy array using the `.reshape()` method.
- Often, we need to convert a row array (`shape = (n, 0)`) into a column array (`shape = (n,1)`)

In [ ]:
# create row
row = np.array([1, 3, 5, 7, 9])
print("Row:", row)
print("Row Shape:", row.shape)

In [ ]:
# reshape to a column
col = row.reshape(-1,1)
print("Column:", col)
print("Column Shape:", col.shape)

## Useful NumPy Functions
Here are examples of basic element-wise arithmetic.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)

- Add and subtract the arrays element by element:

In [ ]:
print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))

- Multiply and divide the arrays element by element:

In [ ]:
print("Multiplication:", np.multiply(a, b))
print("Division:", np.divide(a, b))

- Exponentiate, sum and average an array:

In [ ]:
print("Exponential:", np.exp(a))
print("Sum:", np.sum(b))
print("Mean:", np.mean(a))

- Find the maximum of the array, and the index of the maximum:

In [ ]:
print("Max:", np.max(b))
print("Index of Max:", np.argmax(b))

## Indexing and Slicing
You can retrieve individual elements and slices of arrays.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])

You can also change elements using indexing.

In [ ]:
arr[0] = 99
print("Modified Array:", arr)

Arrays can be populated using loops, just like lists.

In [ ]:
arr = np.zeros(5)
for i in range(5):
    arr[i] = i * 10
print("Array populated with loop:", arr)

## Deep vs Shallow Copies
In computer science, **shallow copy** means copying only the reference to an object, not the actual data. Any change made through one reference will affect the other, because both point to the same memory.

**Deep copy**, on the other hand, creates a new object in memory and copies the data over. This allows changes to the original to not affect the copy.

### Why is this important?
- Shallow copies can lead to **unexpected bugs** when modifying an array.
- This often happens in functions, where a change to a 'copied' array accidentally mutates the original.

`np.copy()` provides a deep copy to prevent this problem.
Let's look at an example to see the difference.

In [ ]:
original = np.array([1, 2, 3])

# make shallow copy
shallow = original

# make deep copy
deep = np.copy(original)

In [ ]:
# modify original
original[0] = 99

print("Original:", original)
print("Shallow Copy:", shallow)
print("Deep Copy:", deep)

# CLASSWORK

### 1. Fill in the Blanks
Fill in the missing words (replacing `????`).

1. NumPy specializes in ????-oriented programming.
1. NumPy arrays are more efficient than Python ???? for numerical operations.
2. The function to create an array from a list is `np.????()`.
3. The shape of a 2D array is given by the `.????` attribute.
4. To perform element-wise addition, use `np.????(a, b)`.
5. To create a deep copy of an array, use `np.????(original)`.
6. The function `np.????` returns the index of the maximum value in the array.

### 2. Array Operations
Create two NumPy arrays `arr1 = [3, 7, 2]` and `arr2 = [45, 0.5, 17.2]` and do the following:
- Add them element-wise
- Multiply them element-wise
- Find the sum and average of each.

### 3. Indexing and Copying
Work with indexing and copies:
- Create a NumPy array called `tens` containing the integers from 10 to 100 (inclusive), with a step of 10
- Slice the middle three elements and print them.
- Make a deep copy, modify the original by setting `tens[3] = 99`, show the deep copy is unchanged

### 4.Row Means and Index of Max

Consider the following 2D NumPy array:

```python
arr = np.array([
    [10, 15, 20, 25],
    [ 5,  8,  6,  7],
    [30, 28, 35, 40]
])
```

  - Print the shape of `arr`.
  - Access the element in the 3rd row, 2nd column.
  - Compute the mean of each row in `arr` and store the results in a list called `means`.
  - Find the row index of the the largest mean.
  - Print both the list of row means and the index with the maximum mean.